---

- name: install postfix
  yum:
    name: postfix

- name: get installed version
  yum:
    list: postfix
  register: postfix_installed_version_getter

- name: set installed version fact
  set_fact:
    postfix_installed_version: >-
      {{ postfix_installed_version_getter.results.0.version }}

- name: remove sendmail
  yum:
    name: sendmail
    state: absent

- name: configure /etc/aliases
  template:
    src: '{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}-aliases.j2'
    dest: /etc/aliases
    owner: root
    group: root
    mode: '0644'
  register: postfix_aliases_configuration

- name: regenerate /etc/aliases.db
  command: newaliases
  when: postfix_aliases_configuration.changed

- name: configure postfix header checks
  copy:
    content: '{{ postfix_header_checks.content }}'
    dest: '{{ postfix_header_checks.dest }}'
    owner: root
    group: root
    mode: 0644
  when: >-
    postfix_header_checks is defined and
    postfix_header_checks.content is defined
  register: postfix_header_checks_configuration

- name: regenerate postfix header checks
  command: 'postmap {{ postfix_header_checks.dest }}'
  when: >-
    postfix_header_checks_configuration is defined and
    postfix_header_checks_configuration.changed and
    (postfix_header_checks.type == "btree" or
    postfix_header_checks.type == "cdb" or
    postfix_header_checks.type == "dbm" or
    postfix_header_checks.type == "hash" or
    postfix_header_checks.type == "lmdb" or
    postfix_header_checks.type == "sdbm")

- name: configure postfix sender canonical mappings
  copy:
    content: '{{ postfix_sender_canonical.content }}'
    dest: '{{ postfix_sender_canonical.dest }}'
    owner: root
    group: root
    mode: 0644
  when: >-
    postfix_sender_canonical is defined and
    postfix_sender_canonical.content is defined
  register: postfix_sender_canonical_configuration

- name: regenerate postfix sender canonical mappings
  command: 'postmap {{ postfix_sender_canonical.dest }}'
  when: >-
    postfix_sender_canonical_configuration is defined and
    postfix_sender_canonical_configuration.changed and
    (postfix_sender_canonical.type == "btree" or
    postfix_sender_canonical.type == "cdb" or
    postfix_sender_canonical.type == "dbm" or
    postfix_sender_canonical.type == "hash" or
    postfix_sender_canonical.type == "lmdb" or
    postfix_sender_canonical.type == "sdbm")

- name: configure postfix smtp generic mappings
  copy:
    content: '{{ postfix_smtp_generic.content }}'
    dest: '{{ postfix_smtp_generic.dest }}'
    owner: root
    group: root
    mode: 0644
  when: >-
    postfix_smtp_generic is defined and
    postfix_smtp_generic.content is defined
  register: postfix_smtp_generic_configuration

- name: regenerate postfix smtp generic mappings
  command: 'postmap {{ postfix_smtp_generic.dest }}'
  when: >-
    postfix_smtp_generic_configuration is defined and
    postfix_smtp_generic_configuration.changed and
    (postfix_smtp_generic.type == "btree" or
    postfix_smtp_generic.type == "cdb" or
    postfix_smtp_generic.type == "dbm" or
    postfix_smtp_generic.type == "hash" or
    postfix_smtp_generic.type == "lmdb" or
    postfix_smtp_generic.type == "sdbm")

- name: configure postfix transport mappings
  copy:
    content: '{{ postfix_transport.content }}'
    dest: '{{ postfix_transport.dest }}'
    owner: root
    group: root
    mode: 0644
  when: >-
    postfix_transport is defined and
    postfix_transport.content is defined
  register: postfix_transport_configuration

- name: regenerate postfix transport mappings
  command: 'postmap {{ postfix_transport.dest }}'
  when: >-
    postfix_transport_configuration is defined and
    postfix_transport_configuration.changed and
    (postfix_transport.type == "btree" or
    postfix_transport.type == "cdb" or
    postfix_transport.type == "dbm" or
    postfix_transport.type == "hash" or
    postfix_transport.type == "lmdb" or
    postfix_transport.type == "sdbm")

- name: configure main.cf
  template:
    src: '{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}-main.cf.j2'
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  register: postfix_main_configuration

- name: reload postfix
  service:
    name: postfix
    state: reloaded
  when: postfix_main_configuration.changed

- name: enable postfix service and assure it is started
  service:
    name: postfix
    enabled: yes
    state: started
  tags:
    - service

...
